#!/usr/bin/env python3
"""Render production `.env` from environment / GitHub Action secrets."""

from __future__ import annotations

import os
from pathlib import Path
from urllib.parse import quote_plus

PLACEHOLDER = "SET_ME"

# Keys written into the server `.env` (app + compose interpolation).
ENV_KEYS = (
    "ASF_ENV",
    "ASF_DEBUG",
    "POSTGRES_PASSWORD",
    "DATABASE_URL",
    "TELEGRAM_BOT_TOKEN",
    "GROQ_API_KEY",
    "OPENAI_API_KEY",
    "STT_PROVIDER",
    "STT_MODEL",
    "LLM_PROVIDER",
    "LLM_MODEL",
    "DISCOVERY_ENGINE",
    "OWNER_TELEGRAM_ID",
    "ASF_ESTIMATE_HOURLY_RATE",
    "ASF_ESTIMATE_CURRENCY",
    "ASF_INTERVENTION_KEY",
    "ASF_INTERVENTION_TTL_HOURS",
    "CURSOR_API_KEY",
    "CURSOR_CLOUD_API_URL",
    "CURSOR_AGENT_REPO",
    "MINIAPP_URL",
    "CONSOLE_TOKEN",
    "UPLOAD_DIR",
    "MAX_UPLOAD_BYTES",
    "ASF_HOST_PORT",
    "DOMAIN_MINIAPP",
    "DOMAIN_CONSOLE",
)


def _clean(value: str | None) -> str:
    text = (value or "").strip()
    if text == PLACEHOLDER:
        return ""
    return text


def is_placeholder(value: str | None) -> bool:
    return _clean(value) in {"", PLACEHOLDER}


def quote_env(value: str) -> str:
    if value == "":
        return ""
    if any(ch in value for ch in ' \t\n#"\'\\$'):
        escaped = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
        )
        return f'"{escaped}"'
    return value


def miniapp_https_url(domain: str) -> str:
    host = _clean(domain).rstrip("/")
    if host.startswith("https://") or host.startswith("http://"):
        host = host.split("://", 1)[1]
    host = host.split("/", 1)[0]
    return f"https://{host}/miniapp/"


def database_url(password: str) -> str:
    return f"postgresql+psycopg://asf:{quote_plus(password)}@db:5432/asf"


def build_env_values(raw: dict[str, str] | None = None) -> dict[str, str]:
    src = {k: _clean(v) for k, v in (raw or os.environ).items()}

    postgres = src.get("POSTGRES_PASSWORD") or src.get("ASF_POSTGRES_PASSWORD") or ""
    if is_placeholder(postgres):
        raise ValueError("POSTGRES_PASSWORD is required (replace GitHub secret SET_ME)")

    domain_miniapp = src.get("DOMAIN_MINIAPP") or ""
    if is_placeholder(domain_miniapp):
        raise ValueError("DOMAIN_MINIAPP is required (replace GitHub secret SET_ME)")

    domain_console = src.get("DOMAIN_CONSOLE") or domain_miniapp
    if is_placeholder(domain_console):
        domain_console = domain_miniapp

    miniapp_url = src.get("MINIAPP_URL") or miniapp_https_url(domain_miniapp)
    host_port = src.get("ASF_HOST_PORT") or "18000"
    if not host_port.isdigit() or not (1 <= int(host_port) <= 65535):
        host_port = "18000"
    stt_provider = src.get("STT_PROVIDER") or "groq"
    stt_model = src.get("STT_MODEL") or "whisper-large-v3-turbo"
    llm_provider = src.get("LLM_PROVIDER") or "stub"
    discovery_engine = (src.get("DISCOVERY_ENGINE") or "auto").lower()
    if discovery_engine not in {"auto", "llm", "fsm"}:
        discovery_engine = "auto"
    console_token = src.get("CONSOLE_TOKEN") or ""
    if is_placeholder(console_token):
        raise ValueError("CONSOLE_TOKEN is required in production (replace GitHub secret SET_ME)")

    values = {
        "ASF_ENV": src.get("ASF_ENV") or "production",
        "ASF_DEBUG": src.get("ASF_DEBUG") or "false",
        "POSTGRES_PASSWORD": postgres,
        "DATABASE_URL": src.get("DATABASE_URL") or database_url(postgres),
        "TELEGRAM_BOT_TOKEN": src.get("TELEGRAM_BOT_TOKEN") or "",
        "GROQ_API_KEY": src.get("GROQ_API_KEY") or "",
        "OPENAI_API_KEY": src.get("OPENAI_API_KEY") or "",
        "STT_PROVIDER": stt_provider,
        "STT_MODEL": stt_model,
        "LLM_PROVIDER": llm_provider,
        "LLM_MODEL": src.get("LLM_MODEL") or "",
        "DISCOVERY_ENGINE": discovery_engine,
        "OWNER_TELEGRAM_ID": src.get("OWNER_TELEGRAM_ID") or "",
        "ASF_ESTIMATE_HOURLY_RATE": src.get("ASF_ESTIMATE_HOURLY_RATE") or "3000",
        "ASF_ESTIMATE_CURRENCY": src.get("ASF_ESTIMATE_CURRENCY") or "RUB",
        "ASF_INTERVENTION_KEY": src.get("ASF_INTERVENTION_KEY") or "",
        "ASF_INTERVENTION_TTL_HOURS": src.get("ASF_INTERVENTION_TTL_HOURS") or "72",
        "CURSOR_API_KEY": src.get("CURSOR_API_KEY") or "",
        "CURSOR_CLOUD_API_URL": src.get("CURSOR_CLOUD_API_URL") or "https://api.cursor.com",
        "CURSOR_AGENT_REPO": src.get("CURSOR_AGENT_REPO") or "",
        "MINIAPP_URL": miniapp_url,
        "CONSOLE_TOKEN": console_token,
        "UPLOAD_DIR": src.get("UPLOAD_DIR") or "/data/uploads",
        "MAX_UPLOAD_BYTES": src.get("MAX_UPLOAD_BYTES") or "20971520",
        "ASF_HOST_PORT": host_port,
        "DOMAIN_MINIAPP": domain_miniapp,
        "DOMAIN_CONSOLE": domain_console,
    }
    return values


def render_env_file(values: dict[str, str]) -> str:
    lines = [
        "# Generated by deploy/write_env.py — do not commit",
        "# ASF production environment",
    ]
    for key in ENV_KEYS:
        lines.append(f"{key}={quote_env(values.get(key, ''))}")
    return "\n".join(lines) + "\n"


def write_env_file(path: Path, raw: dict[str, str] | None = None) -> dict[str, str]:
    values = build_env_values(raw)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_env_file(values), encoding="utf-8")
    return values


def main() -> int:
    target = Path(os.environ.get("ASF_ENV_PATH") or ".env")
    write_env_file(target)
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
